services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://api-gateway:3000
    networks:
      - app-network
    depends_on:
      - api-gateway

  api-gateway:
    build:
      context: ./server/api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CONVERSION_SERVICE_URL=http://conversion-service:3001
      - STORAGE_SERVICE_URL=http://storage-service:3002
      - PORT=3000
    networks:
      - app-network
    depends_on:
      - conversion-service
      - storage-service

  conversion-service:
    build:
      context: ./server/conversion-service
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/wordtopdf
      - STORAGE_SERVICE_URL=http://storage-service:3002
      - PORT=3001
    networks:
      - app-network
    depends_on:
      - mongodb
      - storage-service

  storage-service:
    build:
      context: ./server/storage-service
      dockerfile: Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - MONGODB_URI=mongodb://mongodb:27017/wordtopdf
      - PORT=3002
    networks:
      - app-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: