name: Build and Publish Docker Images

on:
  push:
    branches: [main]
    # Optionally trigger on tags
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]

env:
  REGISTRY: docker.io
  # GitHub environment secrets setup
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  # Add image names with your Docker Hub username
  CLIENT_IMAGE: ${{ secrets.DOCKER_USERNAME }}/word-to-pdf-client
  GATEWAY_IMAGE: ${{ secrets.DOCKER_USERNAME }}/word-to-pdf-gateway
  CONVERSION_IMAGE: ${{ secrets.DOCKER_USERNAME }}/word-to-pdf-conversion
  STORAGE_IMAGE: ${{ secrets.DOCKER_USERNAME }}/word-to-pdf-storage

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      # Build and push Client image
      - name: Build and push Client
        uses: docker/build-push-action@v4
        with:
          context: ./client
          push: true
          tags: |
            ${{ env.CLIENT_IMAGE }}:latest
            ${{ env.CLIENT_IMAGE }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.CLIENT_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.CLIENT_IMAGE }}:buildcache,mode=max

      # Build and push API Gateway image
      - name: Build and push API Gateway
        uses: docker/build-push-action@v4
        with:
          context: ./server/api-gateway
          push: true
          tags: |
            ${{ env.GATEWAY_IMAGE }}:latest
            ${{ env.GATEWAY_IMAGE }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.GATEWAY_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.GATEWAY_IMAGE }}:buildcache,mode=max

      # Build and push Conversion Service image
      - name: Build and push Conversion Service
        uses: docker/build-push-action@v4
        with:
          context: ./server/conversion-service
          push: true
          tags: |
            ${{ env.CONVERSION_IMAGE }}:latest
            ${{ env.CONVERSION_IMAGE }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.CONVERSION_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.CONVERSION_IMAGE }}:buildcache,mode=max

      # Build and push Storage Service image
      - name: Build and push Storage Service
        uses: docker/build-push-action@v4
        with:
          context: ./server/storage-service
          push: true
          tags: |
            ${{ env.STORAGE_IMAGE }}:latest
            ${{ env.STORAGE_IMAGE }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.STORAGE_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.STORAGE_IMAGE }}:buildcache,mode=max
